### PR TITLE
CGFloat now conforms to NMBDoubleConvertible

### PR DESCRIPTION
**Pull request by raphaelcruzeiro**
@norio-nomura Not sure if there's any meaningful test to add to this. What do you think?

### CODE REVIEW

**Comment by norio-nomura** [comment]
If list of types conforming `NMBDoubleConvertible` would exist, it will help user of `beCloseTo()`.
e.g. `testBeCloseToWithNMBDoubleConvertible()` (better name?) containing single line test per type would be such list.

**Comment by norio-nomura** [comment]
`CGFloat` exists on darwin only. https://travis-ci.org/norio-nomura/Nimble/jobs/154448982
We need to use:
```swift
#if os(macOS) || os(iOS) || os(watchOS) || os(tvOS)
```

**Comment by norio-nomura** [comment]
Looks good to me.
@raphaelcruzeiro Do you have any work left?

**Comment by raphaelcruzeiro** [comment]
Not for this branch @norio-nomura

**Comment by norio-nomura** [comment]
Thanks! 🙏

**Pull request merged**
